# -*- coding: utf-8 -*-
MB_BASE_URL = 'https://www.mabangerp.com'
AAMZ_BASE_URL = 'https://aamz.mabangerp.com'
VOTOBO_BASE_URL = 'https://member.votobo.com'
MEMBER_BASE_URL = 'https://member.mabangerp.com'
BIAOJU_BASE_URL = "https://www.i8956.com"


MB_API = f'{MB_BASE_URL}/index.php'
AAMZ_API = f'{AAMZ_BASE_URL}/index.php'
VOTOBO_API = f'{VOTOBO_BASE_URL}/api/index.php'
MEMBER_API = f'{MEMBER_BASE_URL}/api/index.php'
BIAOJU_API = f'{BIAOJU_BASE_URL}/index.php'


COUNTRY_CODE_MAP = {
    'AE': '阿联酋[United Arab Emirates]',
    'AF': '阿富汗[Afghanistan]',
    'AM': '亚美尼亚[Armenia]',
    'AZ': '阿塞拜疆[Azerbaijan Republic]',
    'BD': '孟加拉国[Bangladesh]',
    'BH': '巴林[Bahrain]',
    'BN': '文莱[Brunei Darussalam]',
    'BT': '不丹[Bhutan]',
    'CN': '中国[China]',
    'GE': '格鲁吉亚[Georgia]',
    'HK': '中国-香港[Hongkong, China]',
    'ID': '印尼[Indonesia]',
    'IL': '以色列[Israel]',
    'IN': '印度[India]',
    'IQ': '伊拉克[Iraq]',
    'IR': '伊朗[Iran]',
    'JO': '约旦[Jordan]',
    'JP': '日本[Japan]',
    'KG': '吉尔吉斯斯坦[Kyrgyzstan]',
    'KH': '柬埔寨[Kampuchea Cambodia]',
    'KP': '朝鲜[North Korea]',
    'KR': '韩国[South Korea]',
    'KW': '科威特[Kuwait]',
    'KZ': '哈萨克斯坦[Kazakhstan]',
    'LA': '老挝[Laos]',
    'LB': '黎巴嫩[Lebanon]',
    'LK': '斯里兰卡[Srilanka]',
    'MM': '缅甸[Burma]',
    'MN': '蒙古[Mongolia]',
    'MO': '中国-澳门[Macao China]',
    'MV': '马尔代夫[Maldives]',
    'MY': '马来西亚[Malaysia]',
    'NP': '尼泊尔[Nepal]',
    'OM': '阿曼[Oman]',
    'PH': '菲律宾[Philippines]',
    'PK': '巴基斯坦[Pakistan]',
    'QA': '卡塔尔[Qatar]',
    'SA': '沙特阿拉伯[Saudi Arabia]',
    'SG': '新加坡[Singapore]',
    'SY': '叙利亚[Syria]',
    'TH': '泰国[Thailand]',
    'TJ': '塔吉克斯坦[Tajikistan]',
    'TM': '土库曼斯坦[Turkmenistan]',
    'TP': '东帝汶[Timor Leste]',
    'TR': '土耳其[Turkey]',
    'TW': '中国-台湾[Taiwan, China]',
    'UZ': '乌兹别克斯坦[Uzbekistan]',
    'VN': '越南[Vietnam]',
    'YE': '也门[Yemen]',
    'AA': '美国军队[United States]',
    'AG': '安提瓜和巴布达[Antigua and Barbuda]',
    'BB': '巴巴多斯[Barbados]',
    'BM': '百慕大[Bermuda]',
    'BZ': '伯利兹[Belize]',
    'CA': '加拿大[Canada]',
    'CC': '科科斯岛[Cocos Island]',
    'CR': '哥斯达黎加[Costa Rica]',
    'CU': '古巴[Cuba]',
    'DM': '多米尼加[Dominica]',
    'GD': '格林纳达[Grenada]',
    'GL': '格陵兰岛[Greenland]',
    'GT': '危地马拉[Guatemala]',
    'GU': '关岛[Guam]',
    'HN': '洪都拉斯[Honduras]',
    'HT': '海地[Haiti]',
    'KN': '圣基茨和尼维斯[Saint Kitts and Nevis]',
    'KY': '开曼群岛[Cayman Islands]',
    'LC': '圣卢西亚[Saintlueia]',
    'MH': '马绍尔群岛[Marshall Islands]',
    'MP': '北马里亚纳群岛[Northern Mariana Islands]',
    'MS': '蒙特塞拉特岛[Montserrat]',
    'MX': '墨西哥[Mexico]',
    'NI': '尼加拉瓜[Nicaragua]',
    'PM': '圣皮埃尔和密克隆[Saint Pierre and Miquelon]',
    'PR': '波多黎各[Puerto Rico]',
    'TC': '特克斯和凯科斯群岛[Turks And Caicos Islands]',
    'TT': '特立尼达和多巴哥[Trinidad and Tobago]',
    'UM': '美国外围岛屿[United States Minor Outlying Islands]',
    'US': '美国[United States]',
    'VC': '圣文森特和格林纳丁斯[St Vincent]',
    'VI': '美属维尔京群岛[Virgin Islands]',
    'WS': '萨摩亚[Samoa]',
    'AN': '荷属安的列斯群岛[Antilles]',
    'AR': '阿根廷[Argentina]',
    'AW': '阿鲁巴[Aruba]',
    'BO': '玻利维亚[Bolivia]',
    'BR': '巴西[Brazil]',
    'BS': '巴哈马[Bahamas]',
    'CL': '智利[Chile]',
    'CO': '哥伦比亚[Colombia]',
    'EC': '厄瓜多尔[Ecuador]',
    'FK': '福克兰群岛[Falkland Islands]',
    'GF': '法属圭亚那[French Guiana]',
    'GP': '瓜德罗普[Guadeloupe]',
    'JM': '牙买加[Jamaica]',
    'KI': '基里巴æ¯[Kiribati]',
    'PA': '巴拿马[Panama]',
    'PE': '秘鲁[Peru]',
    'PY': '巴拉圭[Paraguay]',
    'SR': '苏里南[Suriname]',
    'UY': '乌拉圭[Uruguay]',
    'VE': '委内瑞拉[Venezuela]',
    'AS': '美属萨摩亚[American Samoa]',
    'AU': '澳大利亚[Australia]',
    'CK': '库克群岛[Cook Islands]',
    'CX': '圣诞岛[Christmas Island]',
    'FJ': '斐济[Fiji]',
    'FM': '密克罗尼西亚[Micronesia]',
    'IO': '英属印度洋领地[British Indian Ocean Territory]',
    'NC': '新喀里多尼亚[New Caledonia]',
    'NR': '瑙鲁共和国[The Republic of Nauru]',
    'NZ': '新西兰[New Zealand]',
    'PF': '法属波利尼西亚[French Polynesia]',
    'PG': '巴布亚新几内亚[Papuanewguinea]',
    'PW': '帕劳共å国[Palau]',
    'SB': '所罗门群岛[Solomon Islands]',
    'TK': '托克劳群岛(新)[Tokelau]',
    'TO': '汤加[Tonga]',
    'TV': '图瓦卢[Tuvalu]',
    'VG': '英属维尔京群岛[Virgin Islands]',
    'VU': '瓦努阿图[Vanuatu]',
    'WF': '瓦里斯和富士那群岛[Futuna&nbsp;Islands]',
    'AD': '安道尔[Andorra]',
    'AI': '安圭拉[Anguilla]',
    'AL': '阿尔巴尼亚[Albania]',
    'AT': '奥地利[Austria]',
    'BA': '波黑[Bosnia and Herzegovina]',
    'BE': '比利时[Belgium]',
    'BG': '保加利亚[Bulgaria]',
    'BY': '白俄罗斯[Belarus]',
    'CH': '瑞士[Switzerland]',
    'CS': '捷克[Czechrepubic]',
    'CV': '佛得角[Cape Verde]',
    'CW': '库拉索岛[Kulacao]',
    'CY': '塞浦路斯[Cyprus]',
    'CZ': '捷克[Czech Republic]',
    'DE': '德国[Germany]',
    'DK': '丹麦[Denmark]',
    'DO': '多米尼加共和国[Dominican Rep.]',
    'EE': '爱沙尼亚[Estonia]',
    'ES': '西班牙[Spain]',
    'FI': '芬兰[Finland]',
    'FO': '法罗群岛[Faroe Islands]',
    'FR': '法国[France]',
    'GB': '英国[United Kingdom]',
    'GG': '根西岛[Guernsey]',
    'GI': '直布罗陀[Gibraltar]',
    'GR': '希腊[Greece]',
    'HR': '克罗地亚[Croatia, Republic of]',
    'HU': '匈牙利[Hungary]',
    'IE': '爱尔兰[Ireland]',
    'IM': '马恩岛[Isle of Man]',
    'IS': '冰岛[Iceland]',
    'IT': '意大利[Italy]',
    'JE': '泽西岛[Jersey]',
    'LI': '列支敦士登[Liechtenstein]',
    'LT': '立陶宛[Lithuania]',
    'LU': '卢æ£®堡[Luxembourg]',
    'LV': '拉脱维亚[Latvia]',
    'MC': '摩纳哥[Monaco]',
    'MD': '摩尔多瓦[Moldova Republicof]',
    'ME': '黑山[Montenegro]',
    'MK': '马其顿[Macedonia]',
    'MQ': '马提尼克[Martinique]',
    'MT': '马耳他[Malta]',
    'NL': '荷兰[Netherlands]',
    'NO': '挪威[Norway]',
    'PL': '波兰[Poland]',
    'PS': '巴勒斯坦[Palestine]',
    'PT': '葡萄牙[Portugal]',
    'RE': '留尼汪岛[Reunion]',
    'RO': '罗马尼亚[Romania]',
    'RS': '塞尔ç»´亚[Serbia]',
    'RU': '俄罗斯[Russian Federation]',
    'SE': '瑞典[Sweden]',
    'SI': '斯洛文尼亚[Slovenia]',
    'SJ': '斯瓦尔巴群岛[Svalbard archipelago]',
    'SK': '斯洛伐克[Slovakia]',
    'SM': '圣马力诺[Sanmarino]',
    'SV': '萨尔瓦多[El Salvador]',
    'SX': '圣马丁(荷)[Sint Maarten]',
    'UA': '乌克兰[Ukraine]',
    'UK': '英国[United Kingdom]',
    'VA': '梵蒂冈[Vatican]',
    'YK': '科索沃[The Republic of Kosovo]',
    'KS': '科索沃[The Republic of Kosovo]',
    'YT': '马约特岛[Mayotte]',
    'YU': '南斯拉夫联盟[Yugoslavia]',
    'AO': '安哥拉[Angola]',
    'BF': '布基纳法索[Burkinafaso]',
    'BI': '布隆迪[Burundi]',
    'BJ': '贝宁[Benin]',
    'BW': '博茨瓦纳[Botswana]',
    'CD': '刚果(金)[Democratic Republic of Congo]',
    'CF': '中非[Centralafrica]',
    'CG': '刚果(布)[Congo]',
    'CI': '科特迪瓦[Cote Divoire]',
    'CM': '喀麦隆[Cameroon]',
    'DJ': '吉布提[Djibouti]',
    'DZ': '阿尔及©亚[Algeria]',
    'EG': '埃及[Egypt]',
    'ET': '埃塞俄比亚[Ethiopia]',
    'GA': '加蓬[Gabon]',
    'GH': '加纳[Ghana]',
    'GM': '冈比亚[The Republic of the Gambia]',
    'GN': '几内亚[Guinea]',
    'GQ': '赤道几内亚[Equatorial Guinea]',
    'GW': '几内亚比绍[Guinea Bissau]',
    'IC': '加那利群岛[Canary Islands]',
    'KE': '肯尼亚[Kenya]',
    'KT': '科特迪瓦[Coteo Ivoire]',
    'LR': '利比里亚[Liberia]',
    'LS': '莱索托[Lesotho]',
    'LY': '利比亚[Libyan]',
    'MA': '摩洛哥[Morocco]',
    'MG': '马达加斯加[Madagascar]',
    'ML': '马里[Mali]',
    'MR': '毛里塔尼亚[Mauritania]',
    'MU': '毛里求斯[Mauritius]',
    'MW': '马拉维[Malawi]',
    'MZ': '莫桑比克[Mozambique]',
    'NA': '纳米比亚[Namibia]',
    'NE': '尼日尔[Niger]',
    'NG': '尼日利亚[Nigeria]',
    'RW': '卢旺达[Rwanda]',
    'SC': '塞舌尔[Seychelles]',
    'SD': '苏丹[Sudan]',
    'SL': '塞拉利昂[Sierra Leone]',
    'SN': '塞内加尔[Senegal]',
    'SO': '索马里[Somalia]',
    'ST': '圣多美和普林西比[Sao Tome and Principe]',
    'SZ': '斯威士兰[Swaziland]',
    'TD': '乍得[Chad]',
    'TG': '多哥[Togo]',
    'TN': '突尼斯[Tunisia]',
    'TZ': '坦桑尼亚[Tanzania]',
    'UG': '乌干达[Uganda]',
    'ZA': '南非[Southafrica]',
    'ZM': '赞比亚[Zambia]',
    'ZR': '刚果（金）[Zaire]',
    'ZW': '津巴布韦[Zimbabwe]',
    }

CURRENCY_ID_MAP = {
    'US' : 1,
    'USD': 2,
    'EUR': 3,
    'GBP': 4,
    'RMB': 5,
    'AUD': 6,
    'CAD': 7,
    'CNY': 8,
    'JPY': 9,
    'HKD': 10,
    'KRW': 11,
    'TWD': 12,
    'RUB': 13,
    'MYR': 14,
    'PHP': 15,
    'SGD': 16,
    'THB': 17,
    'INR': 18,
    'VND': 19,
    'IDR': 20,
    'BRL': 21,
    'MXN': 22,
    'ARS': 23,
    'TRY': 24,
    'COP': 25,
    'CLP': 26,
    'PNE': 27,
    'NGN': 28,
    'KES': 29,
    'AED': 30,
    'SEK': 32,
    'UGX': 33,
    'NZD': 34,
    'XOF': 35,
    'EGP': 36,
    'AU' : 37,
    'C'  : 38,
    'PLN': 39,
}


EXPORT_FIELD_MAP = {
    # 订单信息类
    '交易编号': 'uq102',
    '备注': 'uq113',
    '物流渠道': 'uq128',
    '货运单号': 'uq130',
    '店铺名': 'uquq135',
    '状态': 'uq136',
    '被合并订单': 'uq191',
    '交运异常原因': 'uq216',
    # 买家信息类
    # 金额类
    # 商品信息类
    '商品数量': 'uq121',
    '平台SKU': 'uq196',
}
